In [2]:
import numpy as np
X = np.array([[25, 2], [5, 26], [3, 7]])
print(X)
print(X.shape)
print(X.size)
print(X[:,0])
print(X[1,:])
print(X[0:2, 0:2])

[[25  2]
 [ 5 26]
 [ 3  7]]
(3, 2)
6
[25  5  3]
[ 5 26]
[[25  2]
 [ 5 26]]
