In [2]:
import numpy as np

x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
print(x)
print(len(x))
print(x.shape)
print(type(x))
x[0] # zero-indexed
type(x[0])

[25  2  5]
3
(3,)
<class 'numpy.ndarray'>


numpy.int64

In [4]:
import numpy as np

# Transposing a regular 1-D array has no effect...
x_t = x.T
print(x_t)
print(x_t.shape)
# ...but it does we use nested "matrix-style" brackets:
y = np.array([[25, 2, 5]])
print(y)
print(y.shape)
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent:
y_t = y.T
print(y_t)
print(y_t.shape) # this is a column vector as it has 3 rows and 1 column
y_t.T
print(y_t.T.shape)
z = np.zeros(3)
print(z)

[25  2  5]
(3,)
[[25  2  5]]
(1, 3)
[[25]
 [ 2]
 [ 5]]
(3, 1)
(1, 3)
[0. 0. 0.]
